.TH IP2LONG 1 "22 May 2010"
.UC 4
.SH 이름
.BI ip2long
\- IPv4 주소를 8byte 정수로 변환
.SH 사용법
.BI "ip2long \-[hv] <" IP " " address "|" hostname "|" long " " ip ">"
.SH 설명
.BI ip2long
명령은 IPv4 주소나 도메인 주소를 8byte 정수형 주소로 변환을 하거나
또는 그 반대로 변환을 한다.
.PP
.SH 옵션
.IP "-v"
기본적으로 ip2long은 변환된 값만 출력을 한다. 이 옵션이 주어지면, 질의한 값과
변환된 값을 모두 출력을 한다.
.IP "-h"
ip2long의 사용법을 출력한다.
.SH 저자
김정균
.SH 버그 리포트
<http://oops.org> 의 QnA 게시판을 이용한다.
.SH 저작권
Copyright (c) 2010 JoungKyun.Kim <http://oops.org>

이 프로그램은
.BI GPL
을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.
