.TH SEARCH 1 "12 Jun 2006"
.UC 4

.SH 이름
kr_search - libkrisp database 에서 IP 에 대한 정보를 검색하여 반환한다.

.SH 사용법
.I #include <krips.h>
.br
.I int kr_search (KRNET_API *isp, KR_API *db);

.SH 설명
kr_search() 함수는 주어진 ip 또는 호스트이름에 대한 정보를 검색한다.
libkrisp 가 GeoIP 를 link 하고 있을 경우, GeoIP database 를 검색을 하려면,
db_argument structure 의 gi 변수에 GeoIP_new 를 선언해 주고, 검색을 하지
않으려면, NULL 을 지정을 한다. GeoIP link 가 되어 있지 않을 경우에도,
gi 변수에 대해서 NULL 로 초기화를 해 주어야만 한다.

.PP
.I #ifdef HAVE_LIBGEOIP
.br
.I db->gi = GeoIP_new (GEOIP_MEMORY_CACHE);
.br
.I #else
.br
.I db->gi = NULL;
.br
.I #endif
.br
.I kr_search (&isp, db);


.SH 반환값
성공시에 0을 반환하며, 실패시에 1을 반환한다. 검색 결과가 없는 것은 성공으로
간주를 한다.

.SH 예제
.nf
#include <krisp.h>
extern char dberr[1024];

int main (void) {
    KR_API db;
    KRNET_API isp;
    char *ip = "168.126.63.1";

	db = (KR_API *) malloc (sizeof (KR_API));

    if ( kr_open (db) ) {
        fprintf (stderr, "ERROR Connect: %s\\n", dberr);
		free (db);
        return 1;
    }

#ifdef HAVE_LIBGEOIP
    db->gi = GeoIP_new (GEOIP_MEMORY_CACHE);
#else
	db->gi = NULL;
#endif

    strcpy (isp.ip, ip);
    kr_search (&isp, db);

	kr_close (db);
	free (db);

    printf ("%-15s %-15s %-20s %-15s %-15s %s\\n",
            ip, isp.ip, isp.icode, isp.network, isp.broadcast, isp.iname);

#ifdef HAVE_LIBGEOIP
    printf ("NATION : %s (%s)\\n", isp.gname, isp.gcode);
#endif

    return 0;
}
.fi

.SH 저자
김정균

.SH 버그 리포트
<http://www.oops.org> 의 QnA 게시판을 이용한다.

.SH 저작권
Copyright (c) 2006 OOPS Development Organization

이 프로그램은 LGPL 을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.

.SH "참고"
krispmkdb(1), krispmkdb(1), krisp_version(3), kr_close(3), kr_search(3)
