.TH KRISPMKDB 1 "11 Jul 2016"

.SH NAME
.BI krispmkdb
\- create database of libkrisp form krisp raw CSV data file.
.SH SYNOPSIS
.BI "krispmkdb -[chty] " saveFile

.SH DESCRIPTION
.BI krispmkdb
 creates libkrisp database from krisp raw csv data file.

.SH OPTIONS
.IP "-c"
Specify csv file for add or update.
.IP "-h"
print usages.
.IP "-t"
Specify table name of database for add or update.
.IP "-y"
Execute with none interactive mode.

.SH AUTHORS
JoungKyun.Kim <http://oops.org>

.SH BUGS
Report to QnA bulletin board of http://oops.org

.SH COPYRIGHT
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

This api is follows
.BI LGPL 2.1

.SH "SEE ALSO"
kr_search(3), kr_search_ex(3)
