.TH KRISP_VERSION 3 "22 May 2010"
.UC 4

.SH 이름
krisp_version - libkrisp 의 버전을 반환한다.

.SH 사용법
.BI "#include <krips.h>"
.br
.BI "char * krisp_version (" void ");"
.br
.BI "char * krisp_uversion (" void ");"

.SH 설명
.BI krisp_version
API는 libkrisp 의 버전을 출력한다.
.PP
.BI krisp_uversion
API는 버전을 정수형으로 표시한다. 각 버전은 3자리씩으로 구현이 되며,
1.1.1 의 경우 001001001 로 반환을 한다.

.SH 예제
.nf
#include <krisp.h>

int main (void) {
    printf ("%s\\n", krisp_version ());
    printf ("%s\\n", krisp_uversion ());

    return 0;
}
.fi

.SH 저자
김정균

.SH 버그 리포트
<http://oops.org> 의 QnA 게시판을 이용한다.

.SH 저작권
Copyright (c) 2010 JoungKyun.Kim <http://oops.org>

이 API는
.BI LGPL
을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.
