#!/bin/sh
#
# $Id: autogen,v 1.8 2011-04-13 09:25:10 oops Exp $
# require autoconf > 2.59 & automake > 1.8
#

opt=

[ "$1" = "--install" ] && opt="$1"

rm -f configure
autoreconf $opt

if [ -n "$opt" ]; then
	rm -rf po ABOUT-NLS
fi

rm -rf autom4te.cache *~

exit 0
