#!/usr/bin/php
<?
#
# $Id: get-domestic-ip,v 1.3 2008-03-14 18:53:59 oops Exp $
#
# get Korea ISP information to text format
#

$original_data = 'http://online.nida.or.kr/link/ISPAllocation.jsp';
#$original_data = 'ISPAllocation.html';

/*
 * Class Section
 */
Class nDom
{
	public $dom;

	function __construct ($f) {
		$context = file_get_contents ($f);

		if ( $context === FALSE ) {
			error_log ("ERROR: URL open failed ($this->url)", 0);
			exit (1);
		}

		$context = $this->decode_entities ($context);

		$this->dom = new DOMDocument ();
		#
		# 메모리에 HTML dom tree 를 load.
		# 주의: loadHTMLFile 은 utf8 로 처리가 된다. 단, 입력 데이터가 iso-8859-1
		#       로 가정을 하기 때문에 출력시에 utf8 을 iso-8859-1 로 변환 시켜야
		#       한다.
		#
		$this->dom->loadHTML ($context);
	}

	function entity ($stream, $tag) {
		return $stream->getElementsByTagName ($tag);
	}

	function str ($stream) {
		return trim (iconv ('utf8', 'iso-8859-1', $stream->textContent));
	}

	function decode_entities ($str) {
		$r = array ('/&nbsp;/');
		$d = array (' ');

		return preg_replace ($r, $d, $str);
	}
}


/*
 * User Code
 */
$dom = new nDom ($original_data);


# get table dom
# ISP 정보는 3번째 table 에 위치함.
$tables = $dom->entity ($dom->dom, 'table');

$tbl_no = 0;
foreach ( $tables as $table ) {
	# ISP 정보는 3번째 테이블이기 때문에 이전 테이블까지는 skip
	if ( $tbl_no++ != 2 )
		continue;

	$trs = $dom->entity ($table, 'tr');

	$tr_no = 0;
	foreach ( $trs as $tr ) {
		# 첫번째 row 는 테이블 헤더이므로 skip
		if ( $tr_no++ < 1 )
			continue;

		$tds = $dom->entity ($tr, 'td');

		unset ($row);
		foreach ( $tds as $td ) {
			$row .= $dom->str ($td) . "\t";
		}

		echo trim ($row) . "\n";
	}
}

?>
