.TH KR_NETWORK 3 "08 Jun 2010"
.UC 4

.SH 이름
kr_network \- IP와 network mask를 이용하여 network address를 반환

.SH 사용법
.BI "#include <krips.h>"
.br
.BI "char * kr_network (ulong " ip ", ulong " mask ");"

.SH 설명
.BI kr_network
API는 IP 주소와 network mask를 이용하여 IP가 포함된 subnet의 network address를 반환한다.

.SH 반환값
.PP
unsigned long 형식의 IP 주소 반환하며, 실패시에
.BI 0
을 반환한다.

.SH 예제
.nf
#include <krisp.h>

int main (void) {
    char * ip = "192.168.10.131";
    char * mask = "255.255.255.192";
    ulong r;

    r = kr_network (kr_ip2long (ip), kr_ip2long (mask));
    printf ("NETWORK ADDRESS: %s\n", kr_long2ip (r));

    return 0;
}
.fi

.SH 저자
김정균 <http://oops.org>

.SH 버그 리포트
<http://oops.org> 의 QnA 게시판을 이용한다.

.SH 저작권
Copyright (c) 2010 JoungKyun.Kim <http://oops.org>

이 API는 
.BI LGPL
을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.

.SH 참조
kr_netmask(3), kr_broadcast(3)
