.TH KR_NETMASK 3 "22 May 2010"
.UC 4

.SH 이름
kr_netmask \- Long IP를 (IPv4) ip 주소로 변환

.SH 사용법
.BI "#include <krips.h>"
.br
.BI "char * kr_netmask (ulong " start ", ulong " end ");"

.SH 설명
.BI kr_netmask
주어진 ip range의 시작 IP와 마지막 IP를 이용하여, 이 IP가 포함된 가장 작은 subnet mask를 반환한다.

.SH 반환값
.PP
성공시에
.BI "IPv4 주소"
형식의 subnet mask long type으로 반환하며, 실패시에
.BI 0
을 반환한다.

.SH 예제
.nf
#include <krisp.h>

int main (void) {
    char * start = "192.168.10.131";
    char * end   = "192.168.10.144";
    ulong r;

    r = kr_netmask (kr_ip2long (start), kr_ip2long (end));
    printf ("SUBNET MASK: %s\n", kr_long2ip (r));

    return 0;
}
.fi

.SH 저자
김정균 <http://oops.org>

.SH 버그 리포트
<http://oops.org> 의 QnA 게시판을 이용한다.

.SH 저작권
Copyright (c) 2010 JoungKyun.Kim <http://oops.org>

이 API는 
.BI LGPL
을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.
