.TH SEARCH 1 "04 Sep 2006"
.UC 4

.SH 이름
kr_search - libkrisp database 에서 IP 에 대한 정보를 검색하여 반환한다.

.SH 사용법
.I #include <krips.h>
.br
.I int kr_search (KRNET_API *isp, KR_API *db);

.SH 설명
kr_search() 함수는 주어진 ip 또는 호스트이름에 대한 정보를 검색한다.
2.0 이전 버전에서 GeoIP 정보를 이용하려면 따로 db->gi 를 관리했어야 하나,
2.0 이후 부터는 kr_open 함수 내부에서 자동으로 처리를 하게 변경이 되었다.
.PP
또한, isp structure member 에 gcity, gretion 이 추가가 되어, GeoIPCity
database 정보 검색이 가능할 경우, 도시, 지역 정보를 같이 제공을 한다.

.PP
.I kr_search (&isp, db);


.SH 반환값
성공시에 0을 반환하며, 실패시에 1을 반환한다. 검색 결과가 없는 것은 성공으로
간주를 한다.

.SH 예제
.nf
#include <krisp.h>
extern char dberr[1024];

int main (void) {
    KR_API db;
    KRNET_API isp;
    char *ip = "168.126.63.1";

	db = (KR_API *) malloc (sizeof (KR_API));

    if ( kr_open (db) ) {
        fprintf (stderr, "ERROR Connect: %s\\n", dberr);
		free (db);
        return 1;
    }

    strcpy (isp.ip, ip);
    kr_search (&isp, db);

	kr_close (db);
	free (db);

    printf ("%-15s %-15s %-20s %-15s %-15s %s\\n",
            ip, isp.ip, isp.icode, isp.network, isp.broadcast, isp.iname);

#ifdef HAVE_LIBGEOIP
    printf ("NATION : %s (%s)\\n", isp.gname, isp.gcode);
    printf ("CITY   : %s %s\\n", isp.gregion isp.gcity);
#endif

    return 0;
}
.fi

.SH 저자
김정균

.SH 버그 리포트
<http://www.oops.org> 의 QnA 게시판을 이용한다.

.SH 저작권
Copyright (c) 2006 OOPS Development Organization

이 프로그램은 LGPL 을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.

.SH "참고"
krispmkdb(1), krispmkdb(1), krisp_version(3), kr_close(3), kr_search(3)
