.TH KR_LONG2IP 3 "22 May 2010"
.UC 4

.SH 이름
kr_long2ip \- Long IP를 (IPv4) ip 주소로 변환

.SH 사용법
.BI "#include <krips.h>"
.br
.BI "char * kr_long2ip (ulong " longip ");"

.SH 설명
.BI kr_long2ip
API는 Long IP(unsigned long type)을 (IPv4) 인터넷 주소(ip address)로 변환을 한다.
.PP
.BI kr_long2ip
API는 정적으로 할당된 버퍼를 반환하기 때문에, 다음에 호출될 때 이 버퍼를
덮어씌우게 되는 것을 주의 하십시오.

.SH 반환값
.PP
성공시에
.BI "IPv4 주소"
값을 반환하며, 실패시에
.BI "0.0.0.0"
을 반환한다.

.SH 예제
.nf
#include <krisp.h>

int main (void) {
    ulong addr = 3232235521;
    char * ip;

    ip = kr_long2ip (addr);
    printf ("IPv4 addr: %s\n", ip);

    return 0;
}
.fi

.SH 저자
김정균

.SH 버그 리포트
<http://oops.org> 의 QnA 게시판을 이용한다.

.SH 저작권
Copyright (c) 2010 JoungKyun.Kim <http://oops.org>

이 API는 
.BI LGPL
을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.
