.TH KRISPMKDB 1 "12 Jun 2006"

.SH 이름
.BI krispmkdb
\- libkrisp 의 database 를 만드는 응용 프로그램
.SH 사용법
.BI "krispmkdb -[chty] " saveFile
.SH 설명
.BI krispmkdb
 libkrisp에서 제공하는 raw csv data file을 이용하여 지정한
database의 table을 갱신하거나 추가하는 도구이다.
.SH 옵션
.IP "-c"
추가 또는 갱신할 csv 파일을 지정한다.
.IP "-h"
krispmkdb 의 사용법을 출력한다.
.IP "-t"
추가 또는 갱신할 table 이름을 지정한다.
.IP "-y"
none interactive mode로 작동한다.
.SH 저자
김정균
.SH 버그 리포트
<http://oops.org> 의 QnA 게시판을 이용한다.
.SH 저작권
Copyright (c) 2013 JoungKyun.Kim <http://oops.org>

이 프로그램은
.BI GPL
을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.

.SH "참고"
kr_search(3), kr_search_ex(3)
