.TH KR_SEARCH_EX 3 "11 Jul 2016"

.SH 이름
kr_search_ex - libkrisp database의 사용자 table을 제어 한다.

.SH 사용법
.BI "#include <krisp.h>"
.sp
.BI "typedef struct raw_netinfos {"
.br
.BI "    char    "  err[1024] "; // get error meassages"
.br
.BI "    char    "  ip[16] ";    // given address"
.br
.BI "    char ** "  dummy ";     // array of 3th field with pipe seperator of table"
.br
.BI "    char *  "  dummydata "; // 3th field strings with pipe seperator of table"
.br
.BI "    ulong   "  start ";     // start of range"
.br
.BI "    ulong   "  end ";       // end of range"
.br
.BI "    bool    "  verbose ";   // verbose option. need initialize"
.br
.BI "    short   "  size ";      // size of dummy member
.br
.BI "} KRNET_API_EX;"
.sp
.BI "int kr_search_ex (KRNET_API_EX *" u_isp ", KR_API *" db ");"

.SH 설명
.BI kr_search
API가 `krisp' table만 다루는 것에 반하여
.BI kr_searhc_ex
API는 이 외의 이름의 table을 다루기 위하여 제공한다. 즉, krisp의 database에
별도의 table을 만들어 관리를 할 수 있다는 의미이다.
.PP
user define table을 생성할 경우에는 db scheme은 다음과 같다.
.PP
.BI "CREATE TABLE ‘user_table_name‘"
.br
.BI "("
.br
.BI "    " start " integer NOT NULL DEFAULT ‘0‘,"
.br
.BI "    " end " integer NOT NULL DEFAULT ‘0‘,"
.br
.BI "    " data " varchar,"
.br
.BI "    PRIMARY KEY (" start " DESC),"
.br
.BI "    UNIQUE (" end ")"
.br
.BI ");"

.PP
libkrisp의 모든 테이블은 모두 동일하게 위의 scheme을 가진다.

.PP
.BI kr_search_ex
API를 사용하기 위해서는 호출 전에
.BI KR_API
struct의 table member와
.BI KRNET_API_EX
struct의 ip member를 초기화 해 주어야 한다.

.PP
.BI kr_search_ex
API는 내부적으로
.BI KRNET_API_EX
의 dummy, dummydata member에 메모리를
할당한다. 그러므로 사용 후에 반드시 메모리를 해제해 주어야 한다.
이를 위해서
.BI initStruct_ex
API를 제공한다. loop에서
.BI kr_searhc_ex
를 사용할 경우, loop 마다
.BI initStruct_ex
를 호출해 주어야 한다.

.PP
.BI "strcpy (" u_isp.ip ", " ipaddress ");"
.br
.BI ""db->table " = " user_define_table ";"
.sp
.BI "kr_search_ex (&" u_isp ", " db ");"
.br
.BI "initStruct_ex (&" u_isp ", " true ");"

.SH 반환값
.PP
성공시에
.BI 0
을 반환하며, 실패시에
.BI 1
을 반환한다. 검색 결과가 없는것은 성공으로 간주를 한다.

.SH 예제
.nf
#include <krisp.h>

int main (void) {
    KR_API * db;
    KRNET_API_EX u_isp;
    char * addr[] = {"kns.kornet.net", "ns.dacom.co.kr"};
    char * database = NULL;
    char err[1024];

    if ( kr_open (&db, database, err) == false ) {
        fprintf (stderr, "ERROR Connect: %s\\n", err);
        return 1;
    }

    u_isp.verbose = false;
    db->table = "geocipy";

    for ( r=0; r<2; r++ ) {
        // defined safecpy_256 in krispapi.h
        safecpy_256 (isp.ip, addr);
        if ( kr_search_ex (&u_isp, db) ) {
            printf ("ERROR: %s\\n", u_isp.err);
            initStruct_ex (&u_isp, true);
            kr_close (&db);
            return 1;
        }

        /*
         * long2ip is include libipcalc.
         * https://github.com/Joungkyun/libipcalc/wiki/API-long2ip
         * long2ip is returned in a statically allocated buffer, which
         * subsequent calls will overwrite. For thread safe, use long2ip_r.
         */
        printf ("%-15s %-15s %-20s", ip, isp.ip, u_isp.dummy[0]);
        printf ("%-15s ", long2ip (u_isp.start));
        printf ("%-15s %s", long2ip (u_isp.end), u_isp.dummy[1]);

        initStruct_ex (&u_isp, true);
    }

    kr_close (&db);

    return 0;
}
.fi

.SH 저자
김정균 <https://joungkyun.github.com>

.SH 버그 리포트
https://github.com/Joungkyun/libkrisp/issues

.SH 저작권
Copyright (c) 2016 JoungKyun.Kim <http://oops.org>

이 API는
.BI LGPL
을 따르며, 사용시의 어떠한 문제에 대하여 보증하지 않는다.

.SH "참고"
kr_open(3), kr_close(3), kr_search_ex(3), long2ip(3)
